<?php
$form = $this->form;
$form->setAttribute('action', $this->url(
    'user/process',
    array(
        'action'     => 'authenticate',
    )
));
$form->prepare();

echo $this->form()->openTag($form);
//echo $this->formCollection($form);
/*echo $this->formLabel($form->get('email')); //display label
echo $this->formInput($form->get('email')); //display input
echo $this->formElementErrors($form->get('email'), array('class' => 'text-error')); //display error*/

echo $this->formRow($form->get('email'));
echo $this->formRow($form->get('password'));
echo $this->formRow($form->get('submit'));
echo $this->form()->closeTag();

if ($this->messages){
    echo '<ul>';
    foreach($this->messages as $message)
    {
        echo '<li>'.$message.'</li>';
    }
    echo '</ul>';
}
?>